### ISSUE TITLE
Consider opt in/out for referrer headers

### ISSUE THREAD

**Issue by jonathanKingston** [WICG/isolation#2]
Commonly on e-commerce setups is the need to allow referrer headers to their payment gateway, could we allow for a permissive list of origins that can receive those headers?

I'm not sure if opener context is also common among these sites too (it should probably not be catered for though).

**Comment by estark37** [comment]
Hi! I'm not sure I understand what you mean. The doc doesn't say anything about referrer headers right now, unless I'm missing something... can you clarify, please?

**Comment by jonathanKingston** [comment]
I think I dreamed the spec covering this topic once sorry about that.
