### ISSUE TITLE
Does per-site process isolation as implemented today address UXSS?

### ISSUE THREAD

**Issue by estark37** [WICG/isolation#4]
Issued raised by @randomdross in spec, moving it here for discussion.

**Comment by estark37** [comment]
Per-site process isolation can mitigate UXSS today, but it's not fully deployed in Chrome today, and it's unlikely to be deployed in the near future in such a way that it'll fully mitigate UXSS, because we can't afford a process for every single site. Isolate-Me gives a site a way to request to opt in to per-site process isolation.

(Moreover, per-site process isolation is a Chrome feature, not a web platform concept, so we can't really rely upon it existing in the spec.)

**Comment by randomdross** [comment]
Got it, thank you!
